ID_Error = 100;
// Binary
ID_Data = 101;
// String
ID_UserName = 102;
// Integer
ID_UserID = 103;
// Integer
ID_UserIconID = 104;
// String
ID_UserLogin = 105;
// String
ID_UserPW = 106;
// Integer
ID_RefNum = 107;
// Integer
ID_XferSize = 108;
// Integer
ID_ChatOptions = 109;
// Binary - This field is represented as 64-bit bitmap.
ID_UserAccess = 110;
ID_UserAlias = 111;
// Integer - User flags field is a bitmap with the following values:
// 1 - away, 2 - admin/disconnected, 4 - refuses PMs, 8 - refuses private chat
ID_UserFlags = 112;
// Integer
ID_Options = 113;
// Integer
ID_ChatID = 114;
// String
ID_ChatTopic = 115;
// Integer
ID_QueueSlot = 116;
ID_ServerTOS = 150;
// Binary
ID_Banner = 151;
// Integer - This field can have one of the following values:
// 1 - URL, 3 - JPEG, 4 - GIF, 5 - BMP, 6 - PICT
ID_BannerType = 152;
// Binary
ID_BannerURL = 153;
// Integer - The value of this field is 1 if there is no agreement to be sent.
ID_NoServerTOS = 154;
// Integer
ID_Version = 160;
// Integer
ID_BannerID = 161;
// Binary
ID_ServerName = 162;
// THLFileInfo
ID_FileInfo = 200;
// String
ID_FileName = 201;
// THLPath
ID_FilePath = 202;
// THLFileResume
ID_FileResume = 203;
// Integer
ID_FileXferOptions = 204;
// String
ID_FileTypeStr = 205;
// String
ID_FileMakerStr = 206;
// Integer
ID_FileSize = 207;
// THLDate
ID_FileMakeDate = 208;
// THLDate
ID_FileModDate = 209;
// String
ID_FileBlurb = 210;
// String
ID_FileNewName = 211;
// Binary
ID_FileNewPath = 212;
// Binary[4]
ID_FileType = 213;
// Binary
ID_Quote = 214;
// String
ID_AutoReply = 215;
// Integer
ID_DirItemCount = 220;
// THLUserInfo
ID_UserInfo = 300;
ID_NewsCatGUID = 319;
// THLNewsCategoriesData1
ID_NewsCatsDataV1 = 320;
// THLNewsArticlesData
ID_NewsArtsData = 321;
// String
ID_NewsCatName = 322;
// THLNewsCategoriesData2
ID_NewsCatsDataV2 = 323;
// THLPath
ID_NewsPath = 325;
// Integer
ID_NewsArtID = 326;
// String
ID_NewsArtMIME = 327;
// String
ID_NewsArtTitle = 328;
// String
ID_NewsArtPoster = 329;
// THLDate
ID_NewsArtDate = 330;
// Integer
ID_PrevArtID = 331;
// Integer
ID_NextArtID = 332;
// Binary
ID_NewsArtData = 333;
// Integer
ID_NewsArtFlags = 334;
// Integer
ID_ParentArtID = 335;
// Integer
ID_1stChildArt = 336;
{ (Delete Children) }
ID_NewsArtDelChildren = 337;
	